name: Build

on:
  push: {}
  pull_request: {}
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Build project
        run: ./gradlew build --scan

      - name: Archive Jar artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Agent
          path: agent/build/ci

      - name: Upload artifact (javaagent)
        if: "${{ github.event_name == 'release' }}"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./agent/build/ci/agent.jar
          asset_name: jvm-hook-framework-javaagent-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/jar

      - name: Upload artifact (api)
        if: "${{ github.event_name == 'release' }}"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./agent/build/ci/api.jar
          asset_name: jvm-hook-framework-api-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/jar

